services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"

    environment:
      MONGO_URI: mongodb+srv://praveen:Patty%40%23%2445@cluster0.itzidor.mongodb.net/FIXIT

  frontend:
    build: ./frontend
    ports:
      - "3001:80"