

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb+srv://praveen:Patty%40%23%2445@cluster0.itzidor.mongodb.net/FIXIT"
    networks:
      - fixit-network

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    networks:
      - fixit-network

  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - fixit-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - fixit-network
    depends_on:
      - prometheus

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    user: root
    privileged: true
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - fixit-network

networks:
  fixit-network:
    driver: bridge