apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: praveen6235/fixit-backend:latest

          ports:
            - containerPort: 5000

          env:
            - name: MONGO_URI
              value: "mongodb+srv://praveen:Patty%40%23%2445@cluster0.itzidor.mongodb.net/FIXIT"